// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwxaxbpyskupletlydch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eGF4YnB5c2t1cGxldGx5ZGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODAyNzksImV4cCI6MjA2Mzg1NjI3OX0.NJMDI4qn7vsiMsM13hiZpfayONWM4jPDLRgbwH5DvoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);